
services:
  # 1. КОНТЕЙНЕР БАЗЫ ДАННЫХ
  postgres_db:
    image: postgres:15-alpine
    container_name: store_postgres
    environment:
      POSTGRES_DB: romanramazanov
      POSTGRES_USER: romanramazanov
      POSTGRES_PASSWORD: 19082009 # Придумай тут пароль для базы внутри докера, придумал
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. КОНТЕЙНЕР НАШЕГО JAVA-ПРИЛОЖЕНИЯ
  java_app:
    build: .
    container_name: store_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db # Говорим Спрингу: "Жди, пока запустится база данных"
    environment:
      # Меняем адрес базы! Вместо localhost пишем имя сервиса из докера — postgres_db
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/romanramazanov
      SPRING_DATASOURCE_USERNAME: romanramazanov
      SPRING_DATASOURCE_PASSWORD: 19082009
      # Передаем твои токены Телеграма прямо внутрь контейнера
      TELEGRAM_BOT_TOKEN: "8841829549:AAHL8lZr8n6pqi7woLYI2MbycbcOOb_pDsk"
      TELEGRAM_BOT_CHAT_ID: "648887825"

volumes:
  pgdata: # Это нужно, чтобы при перезапуске докера данные в базе не стирались