spring.application.name=ApiTelegramStore

# Подключение к твоей базе из Postgres.app
spring.datasource.url=jdbc:postgresql://localhost:5432/romanramazanov
spring.datasource.username=romanramazanov
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Магия Hibernate: автоматически создать таблицу products при старте
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true