spring.application.name=api-telegram-store

spring.datasource.url=jdbc:postgresql://localhost:5432/romanramazanov
spring.datasource.username=romanramazanov
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Указываем путь к SQL файлу
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.sql

# Насильно заставляем Liquibase запуститься, даже если Спринг сомневается
spring.liquibase.enabled=true
# Уровень логов для Liquibase выставляем на максимум (DEBUG), чтобы видеть вообще каждый его вздох
logging.level.org.liquibase=DEBUG
