spring.application.name=api-telegram-store

spring.datasource.url=jdbc:postgresql://localhost:5432/romanramazanov
spring.datasource.username=romanramazanov
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Отключаем авто-создание от Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Настройки заглавного SQL в логах
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.query.compile.uppercase_keyword=true

# Включаем Liquibase и указываем путь к новому YAML-мастеру
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml

